server:
  port:  9000
spring:
  application:
    name:  rank-service
  #main:
    #allow-bean-definition-overriding: true
  jpa:
    database:  MYSQL
  datasource:
    url:  jdbc:mysql://localhost:3306/test?autoReconnect=true&amp;failOverReadOnly=false
    username:  root
    password:  123456aaa
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address:  true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: false
    fetch-registry: false